# --- First database schema

# --- !Ups

set ignorecase true;

create table company (
  "id"                        bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "name"                      varchar(255) not null)
;

create table computer (
  "id"                        bigint GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "name"                      varchar(255) not null,
  "introduced"                timestamp,
  "discontinued"              timestamp,
  "company_id"                bigint)
;

alter table computer add constraint fk_computer_company_1 foreign key ("company_id") references company ("id") on delete cascade on update cascade;


# --- !Downs

SET REFERENTIAL_INTEGRITY FALSE;

drop table if exists company;

drop table if exists computer;

SET REFERENTIAL_INTEGRITY TRUE;

drop sequence if exists company_seq;

drop sequence if exists computer_seq;

